### PR TITLE
API improvements

### PR DESCRIPTION
**Pull request by notxcain**
Hi! 
First of all thanks for this library. 

I've found a couple of naming and interface inconsistencies with HTTP status code metrics. To demonstrated how it could be improved I've created a separate trait named  `StatusCodeMetrics`.
What's new:
* Use `akka-http` terminology,  i.e. `status code` instead of `response code`  (see `akka.http.scaladsl.model.StatusCode`).
* Use directive naming consistent with other directives in akka, e.g. `withStatusCodeCounter`, it's the same pattern as `withLog`, `withSettings`, etc.
* Counter directives no longer require implicit `ExecutionContext`, it is obtained using `extractExecutionContext` directive. If there was some reason behind requiring it in the first place (like blocking calls or something) please correct me.

I've also removed unused imports and renamed `test/scala/ResponseCodeMetrics.scala` to `test/scala/ResponseCodeMetricsSpec.scala` to be consistent.

If you find this changes useful, and you don't want to break API, there is a duplicate code in `StatusCodeMetrics` and `ResponseCodeMetrics` that could be extracted to a common trait.

### CODE REVIEW

**Comment by adamdecaf** [comment]
Hey @notxcain! Thanks for the PR. I assume some of the verbage choices were from the spray/akka-http beta days (or just my own ramblings). This some pretty good cleanup that I'll get merged in. I'm thinking that this should go in a 0.5.0 release with deprecation warnings (and sharing code).

**Comment by adamdecaf** [comment]
I've released `0.5.0` with these changes. Thanks!

**Comment by notxcain** [comment]
@adamdecaf awesome! Thank you very much!

**Comment by notxcain** [comment]
@adamdecaf BTW what do you think about renaming `HttpMeterMetrics#meterDirective` to `withMeter` and `HttpMeterMetrics#meterDirectiveWithName` to `withMeterNamed`, adding proper deprecation annotation? I can send a PR, if it's ok with you.

**Comment by adamdecaf** [comment]
@notxcain Yea. Those names sound much better and seem to flow better with the existing names. I'll accept a PR. 

http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/alphabetically.html

**Comment by notxcain** [comment]
@adamdecaf cool! What do you think about renaming traits, adding `Directives` suffix, it seems to be consistent with `akka-http`?

**Comment by notxcain** [comment]
Anyway I'll send a PR with first batch of changes, and then we'll see :)

**Comment by adamdecaf** [comment]
To have `MeterDirectives` and `TimerDirectives`? That does make more sense. Feel free to add that in with deprecation notices on the older trait names.

**Comment by notxcain** [comment]
That's great, will do. I just feel that it will make usage of the library more pleasant for new comers. Especially given that it's the first line of Google search results for `akka http metrics` :)

**Pull request merged**
