### PR TITLE
Support custom reservoirs

### PR DESCRIPTION
**Pull request by adamdecaf**
Cherry-picked [the bulk of the change](https://github.com/Backline/akka-http-metrics/pull/6/commits/7f8b3005536372f459d1b1cd065c5d4fd5cd59ba) from https://github.com/Backline/akka-http-metrics/pull/6

### CODE REVIEW

**Comment by queirozfcom** [comment]
Cool! Do you think it's possible to do it for the `meter` part of the timer as well? I see you've created a method called `findandregistermeter` but I don't see where it's used; plus I'm not sure that the meter takes a custom reservoir.. does it?

**Comment by queirozfcom** [comment]
Ideally I would like to be able to customize the logged string so that the `count=` part of the logged message also is reset for each sampling. I think this is a somehow common request and I'm not sure it's solvable. Actually I used a custom reservoir for the Timer to solve this problem and it's solved it for the timings but not yet for the counts... =(

**Comment by adamdecaf** [comment]
@queirozfcom Just getting back to this. Is this something you're still interested in having? I can fix up this PR if so.

**Comment by queirozfcom** [comment]
Hi @adamdecaf thanks for the reply. Actually, I ended up using `nl.grons.metrics-scala` because I didn't think your lib was measuring the actual time takes by the actor messages to be answered. It's possible I was doing something wrong so I'll try it again in the future.

As for the reservoir, I'm using `"org.mpierce.metrics.reservoir" % "hdrhistogram-metrics-reservoir" % "1.1.2"` but in order to have the counts be reset after each snapshot I had to hack `Sl4jReporter` to report `snapshot.size()` rather than `timer.getCount()` as the number of messages received within the last snapshot.

This is more complicated than it seems I guess, there's tons of Issues and rejected PRs in Coda Hale's metrics related to this. It ended up being more trouble than it's worth actually.

**Comment by adamdecaf** [comment]
@queirozfcom If you're using Future's it won't [be measuring properly](https://github.com/Backline/akka-http-metrics/issues/13), however all other calls should be *approximately* the same as the time in the akka-http Actor/Stream.

**Comment by adamdecaf** [comment]
@queirozfcom In 0.4.2 we shipped a fix for timing futures fyi. 

https://github.com/Backline/akka-http-metrics/releases/tag/0.4.2

**Pull request closed without merging**
